import { Router } from "express";
import path from "node:path";
import { asyncHandler } from "../../utils/asyncHandler";
import { ApiError } from "../../utils/ApiError";
import { getObjectByKey } from "../../lib/storage";

export const filesRouter = Router();

// Keys are generated by uploadBuffer as `<folder>/<32 hex chars><ext>`, so
// anything outside this shape is not something we wrote. Rejecting by shape
// (rather than only stripping "..") keeps path traversal away from the local
// disk backend, where the key becomes part of a filesystem path.
const SAFE_KEY = /^[A-Za-z0-9][A-Za-z0-9._-]*(\/[A-Za-z0-9][A-Za-z0-9._-]*)*$/;

const MIME_BY_EXT: Record<string, string> = {
  ".pdf": "application/pdf",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".webp": "image/webp",
  ".gif": "image/gif",
  ".svg": "image/svg+xml",
};

/**
 * Serves teacher-uploaded PDFs and microscope images through the app's own
 * origin instead of the storage backend's hostname. Public on purpose — these
 * are the same files students load inside materi pages, and the keys carry 16
 * random bytes, so they are unguessable without a link.
 */
filesRouter.get(
  "/*",
  asyncHandler(async (req, res) => {
    const raw = (req.params as Record<string, string>)[0] ?? "";
    let key: string;
    try {
      key = decodeURIComponent(raw);
    } catch {
      throw ApiError.notFound("File tidak ditemukan");
    }

    if (!SAFE_KEY.test(key)) throw ApiError.notFound("File tidak ditemukan");

    const object = await getObjectByKey(key);
    if (!object) throw ApiError.notFound("File tidak ditemukan");

    const ext = path.extname(key).toLowerCase();
    res.setHeader("Content-Type", object.contentType ?? MIME_BY_EXT[ext] ?? "application/octet-stream");
    if (object.contentLength !== undefined) res.setHeader("Content-Length", String(object.contentLength));
    // A key is minted once per upload and never reused, so the bytes behind
    // this URL can never change — cache hard, and spare the free-tier instance
    // from re-serving the same slide image to every student in a class.
    res.setHeader("Cache-Control", "public, max-age=31536000, immutable");

    object.stream.on("error", () => res.destroy());
    object.stream.pipe(res);
  })
);
